augment: true
b1: 0.9
b2: 0.999
batch_size: 4
channels: 3
checkpoint_interval: 500
dataset_name: img_align_celeba
decay_epoch: 100
degradation_mode: bicubic
device: cuda
ema_decay: 0.999
filters: 64
gradient_clipping: 1.0
hr_height: 256
hr_width: 256
lambda_adv: 0.005
lambda_perceptual: 1.0
lambda_pixel: 0.01
lambda_tv: 1.0e-06
lr: 0.0001
mixed_precision: true
n_cpu: 8
n_epochs: 200
num_res_blocks: 23
num_upsample: 2
sample_interval: 100
scale_factors:
- 4
use_attention: true
use_spectral_norm: false
use_wandb: false
warmup_batches: 500
